export const SETTINGS_DATA = {
  "current": {
    "enable_global_bar": false,
    "global_bar_text": "FREE EXPRESS HOLIDAY SHIPPING THROUGH WEDNESDAY! Trust, us, we give good gift.",
    "global_bar_link": "#",
    "global_bar_bg": "#000000",
    "flyout_empty_title": "Shop the<br>monogram collection",
    "flyout_promo": "",
    "flyout_empty_cta": "Explore Now",
    "flyout_empty_link": "shopify://collections/monogram",
    "slider_auto": true,
    "slider_show_dots": true,
    "slider_show_arrows": true,
    "slider_rate": "3000",
    "slider_transition": "fade",
    "base_color": "#000000",
    "headline_color": "#000000",
    "link_color": "#000000",
    "accent_color": "#607d80",
    "billboard_text_dark": "#000000",
    "billboard_text_light": "#ffffff",
    "color_swatches": "blue:0000cd\nred:991122\ngreen:006400\nnavy:062e56\nyellow:f8de7e\nblack:000000\nwhite:ffffff\ncreamold:fffff0\ncream:fff5d0\nbrightblue:003366\ngrey:666666\nburgundy:800020\nlightgrey:F8F8F8\nwhite-pearl:eeebe2\npaleblue:BDDEFF\npalepink: fadadd\npalepink: fadadd\npurple: 421C52\nblack/white:000000/ffffff",
    "embroidery_swatches": "black:101820\nblue:0033a0\nblush:ffbe9f\nnavy:2c3540\nred:c8102e\nwhite:f2e9ea\npaleblue:BDDEFF\npalepink: fadadd\npurple: 421C52",
    "anniversary_embroidery_swatches": "black:101820\nnavy:2c3540\nred:c8102e\nblue:0033a0\ncream:fff5d0",
    "logo_use_image": false,
    "favicon_enable": false,
    "favicon": "",
    "secondary_menu": "secondary-menu",
    "menu_mobile": "menu-mobile",
    "dropdown_mode": "light",
    "nav_dark": "#000000",
    "nav_dark_text": "#ffffff",
    "nav_light": "#ffffff",
    "nav_light_text": "#000000",
    "navigation_mega_menu_1": "Dresses",
    "mega_1_pic_1": "shopify://shop_images/Rectangle_3.png",
    "mega_1_text_1": "Little white dress",
    "mega_1_pic_2": "shopify://shop_images/Screen_Shot_2022-06-03_at_1.03.35_PM.png",
    "mega_1_text_2": "Patterned DRESSES",
    "mega_1_link_2": "#",
    "mega_1_pic_3": "shopify://shop_images/Screen_Shot_2022-06-03_at_1.03.35_PM.png",
    "mega_1_text_3": "SUMMER DRESSES",
    "mega_1_link_3": "#",
    "navigation_mega_menu_3": "Stories",
    "mega_3_pic_1": "shopify://shop_images/Paulina1_2048x2048_1.png",
    "mega_3_text_1": "LA STORY",
    "mega_3_des_1": "Starring supermodel, author and “occasional actress” Paulina Porizkova",
    "mega_3_pic_2": "shopify://shop_images/Paulina1_2048x2048_3.png",
    "mega_3_text_2": "WOKE UP LIKE THIS",
    "mega_3_des_2": "Amy Schumer in her natural habitat (bed).",
    "button_label": "View all",
    "button_link": "shopify://collections",
    "nav_1_mobile_pic": "shopify://shop_images/20190715_ATY_LALIGNE_06_047-ATY2_2048x2048_07f1fe9c-704e-4267-854c-3c9dfed74bef.png",
    "nav_1_mobile_pic_sec": "shopify://shop_images/20190715_ATY_LALIGNE_01_403-ATY2_2048x2048_2df1ed14-dc36-44d0-be70-a9919392960d.png",
    "nav_2_mobile_pic": "shopify://shop_images/Martha_5_2048x2048_960ab951-4e34-4235-bd6f-0c3df3292d4d.jpg",
    "nav_2_mobile_pic_sec": "",
    "nav_3_mobile_pic": "shopify://shop_images/04_022619_094_copy_2048x2048_3b6dfbb6-b15a-4c8c-a8e5-783525ef81b9.jpg",
    "nav_3_mobile_pic_sec": "",
    "nav_4_mobile_pic": "shopify://shop_images/02_100118_0236_2048x2048_fdcf5994-8a2e-429a-bab4-c6f4058804d8.jpg",
    "nav_4_mobile_pic_sec": "",
    "nav_5_mobile_pic": "shopify://shop_images/mega_1_img.jpg",
    "nav_5_mobile_pic_sec": "",
    "nav_6_mobile_pic": "shopify://shop_images/20190715_ATY_LALIGNE_01_463-ATY_2048x2048.progressive_7dfc52a9-672b-410a-b41e-f7167f6a8c75.jpg",
    "footer_newsletter_enable": true,
    "footer_newsletter_title": "Line up & we'll share.",
    "footer_menu_enable": true,
    "list_id": "LP4TpV",
    "success_message": "Merci and welcome to La Bande!",
    "error_message": "You're already a part of the family!",
    "footer_menu_1": "customer-care",
    "footer_menu_2": "about-la-ligne",
    "footer_menu_3": "terms-and-conditions",
    "home_enable_video": true,
    "collection_enable_video": false,
    "global_video_placeholder": "shopify://shop_images/featured_content_2_pic.jpg",
    "global_video_placeholder_title": "Title",
    "global_video_placeholder_text": "Text",
    "global_video_mp4": "https://player.vimeo.com/external/325949869.hd.mp4?s=d0f951c88c2e1ec189973cd68d26ae5b85310a9f&profile_id=175",
    "global_video_ogv": "",
    "global_video_webm": "",
    "pre_billboard_img": "shopify://shop_images/20190715_ATY_LALIGNE_01_463-ATY_2048x2048.progressive_7dfc52a9-672b-410a-b41e-f7167f6a8c75.jpg",
    "stories_img": "",
    "stories_img_alt": "",
    "stories_img_headline": "Stories",
    "stories_img_text": "An editorial take on our seasonless stripes.",
    "stories_img_color": "light",
    "in_line_img": "shopify://shop_images/ArielleCharnas_LaLigneDec18_0286_HEADER_FINAL_BW_web_2048x2048_caf817f6-8f76-4905-98d0-7a19a313248a.png",
    "in_line_alt": "In Line",
    "in_line_headline": "In Line",
    "in_line_subhead": "They styled it. We shot it. <br>\nMeet the women who make La Ligne their own.",
    "in_line_align": "left",
    "in_line_color": "light",
    "in_line_content_pre": "NEXT IN LINE",
    "in_line_content_text": "Visit us every week to meet more members of the bande.",
    "inline_enable_video": false,
    "inline_video_placeholder": "shopify://shop_images/02_100118_0236_2048x2048_fdcf5994-8a2e-429a-bab4-c6f4058804d8.jpg",
    "inline_video_placeholder_title": "Behind the Scenes",
    "inline_video_placeholder_text": "Why we are.<br>\nWho we are. What we are.",
    "inline_video_mp4": "//res-1.cloudinary.com/lalignenyc/video/upload/q_80,vc_auto/y2sg7jtdlg82oksaazic.mp4",
    "inline_video_ogv": "//res-1.cloudinary.com/lalignenyc/video/upload/q_80,vc_auto/y2sg7jtdlg82oksaazic.ogv",
    "inline_video_webm": "//res-1.cloudinary.com/lalignenyc/video/upload/q_80,vc_auto/y2sg7jtdlg82oksaazic.webm",
    "inline_enable_featured_profiles": true,
    "about_section_1": "about-intro",
    "about_section_2": "about-team",
    "about_section_3": "about-promo-1",
    "about_section_4": "about-promo-2",
    "about_section_5": "about-promo-3",
    "about_section_6": "about-pledge",
    "about_section_7": "about-inspiration",
    "about_banner": "shopify://shop_images/ArielleCharnas_LaLigneDec18_0286_HEADER_FINAL_BW_web_2048x2048_caf817f6-8f76-4905-98d0-7a19a313248a.png",
    "about_banner_headline": "Behind the Label",
    "about_banner_text": "Take a peek behind the scenes and meet the team.",
    "about_text_block_headline": "This is the new Text Block",
    "about_text_block_text": "This is the new text",
    "about_content_block_1_img": "shopify://shop_images/mega_1_img.jpg",
    "about_content_block_1_headline": "We wanna be on you",
    "about_content_block_1_text": "La Ligne starts with the iconic stripe but doesn't stop there. You'll find everyday essentials and statement pieces - versatile staples that can be effortlessly styled together from dawn to dusk. If you can’t eat, dance, sleep and drink in it, we won’t make it. And while some clothes stay and some go, these are the ones that stick around. The only thing “fast” about our fashion is how quickly they will arrive at your doorstep.",
    "about_content_block_1_cta": "Shop our collection",
    "about_content_block_1_link": "/collections/all",
    "about_content_block_2_img": "shopify://shop_images/mega_1_img.jpg",
    "about_content_block_2_headline": "At Your Service",
    "about_content_block_2_text": "Wondering how to wear your stripes? La Ligne Styliste ensures you never get \"stuck\" in your stripes. Email us your styling Qs at styliste@lalignenyc.com and receive a response from our Vogue-alum co-founders, Valerie Macaulay & Meredith Melling, within 72 hours.",
    "about_content_block_2_cta": "HELP ME STYLE MY STRIPES",
    "about_content_block_2_link": "mailto:styliste@lalignenyc.com",
    "about_content_block_3_img": "shopify://shop_images/mega_1_img.jpg",
    "about_content_block_3_headline": "Take it personally",
    "about_content_block_3_text": "We love when women wear La Ligne and make it their own. Now you can customize your favorite La Ligne items with our signature monogram — inspired by the tradition of crossing out one's name on personalized stationery to indicate a more casual, friendly relationship with the recipient. We loved this idea of “slashing” through our monogram treatment to take the element of customization a step further — so go ahead and take it personally.",
    "about_content_block_3_cta": "Shop Monogram",
    "about_content_block_3_link": "/collections/monogram-story",
    "the_team_text": "We want to infuse a sense of fun into our collections. We don't want to be precious with fashion.",
    "founder_1": "shopify://shop_images/Screen_Shot_2019-10-28_at_11.33.28_AM.png",
    "founder_2": "shopify://shop_images/2_a7f82a8f-7381-4682-b27e-64716c92017e.jpg",
    "founder_3": "shopify://shop_images/3_bca53126-a366-46ea-b4de-d8cf730edafa.jpg",
    "founders_headline": "The Founders",
    "founders_text": "Take one iconic graphic and add a lifetime of fashion savvy and you’ll find team La Ligne. Former Vogue editors Valerie Macaulay and Meredith Melling, and Molly Howard, rag &amp; bone’s former head of business development, have earned their fashion stripes. They joined forces with one goal: translate the stripe into a collection that would empower women of all ages with effortless self-expression.",
    "enable_video": true,
    "video_placeholder": "",
    "video_placeholder_title": "Behind the scenes",
    "video_placeholder_text": "Watch La Ligne come to life.",
    "video_mp4": "http://res-1.cloudinary.com/lalignenyc/video/upload/q_80,vc_auto/y2sg7jtdlg82oksaazic.mp4",
    "video_ogv": "",
    "video_webm": "",
    "shop_promo": "",
    "shop_promo_headline": "At Your Service",
    "shop_promo_text": "Wondering how to wear your <br> stripes? La Ligne Styliste ensures <br> you never get \"stuck\" in your stripes. <br> Email us your styling Qs and receive a response from our Vogue-alum co-founders, Valerie Macaulay & Meredith Melling, within 72 hours.",
    "shop_promo_cta": "Shop all",
    "shop_promo_link": "/collections/all",
    "pledge_headline": "Our Pledge",
    "pledge_text": "6.11.2020 <br> We stand in solidarity with the Black Lives Matter movement and are committed to combating racism, both as a brand and as individuals. We vow to educate ourselves, to take action and to be transparent about our efforts going forward in the fight for racial equity. The following initiatives are some of the actions we have taken as well as our pledges for the future and this is just the beginning.",
    "pledge_cta": "Read More",
    "pledge_link": "our-pledge",
    "contact_billboard": "",
    "contact_billboard_headline": "Drop us a Line",
    "contact_billboard_text": "Here's how to contact us.",
    "contact_block_1": true,
    "contact_block_1_img": "",
    "contact_block_1_headline": "Customer Service",
    "contact_block_1_text": "We look forward to hearing from you! If you’re calling about an order, please have your confirmation number ready.",
    "contact_block_1_cta": "lou@lalignenyc.com",
    "contact_block_1_link": "mailto:lou@lalignenyc.com",
    "contact_block_1_phone": "(917) 979-2680",
    "contact_block_2": true,
    "contact_block_2_img": "",
    "contact_block_2_headline": "Is This Pressing?",
    "contact_block_2_text": "For press inquiries, please email:",
    "contact_block_2_cta": "laligne@derris.com",
    "contact_block_2_link": "mailto:laligne@derris.com",
    "contact_block_2_phone": "",
    "contact_block_3": true,
    "contact_block_3_img": "",
    "contact_block_3_headline": "We're Hiring",
    "contact_block_3_text": "Have you earned your e-commerce stripes? We’re seeking talented people to join our fast-growing company. Email your résumé to:<br>",
    "contact_block_3_cta": "jobs@lalignenyc.com",
    "contact_block_3_link": "mailto:jobs@lalignenyc.com",
    "contact_block_3_phone": "",
    "contact_block_4": true,
    "contact_block_4_img": "",
    "contact_block_4_headline": "En Ligne",
    "contact_block_4_text": "Follow us, share us, like us.",
    "contact_block_4_cta": "@lalignenyc",
    "contact_block_4_link": "https://www.instagram.com/lalignenyc/",
    "contact_block_4_phone": "",
    "career_billboard": "shopify://shop_images/JoAni_Johnson_La_Ligne_La_Bande_SEPT_2019_Set_1_227_FINAL_web.jpg",
    "career_billboard_headline": "We are Hiring",
    "career_billboard_text": "La Ligne is a pretty fun place to work.",
    "career_block": true,
    "career_block_img": "shopify://shop_images/Screen_Shot_2021-07-19_at_5.00.42_PM.png",
    "career_block_headline": "Get in Touch",
    "career_block_text": "Our customer-first mentality allows each employee to make an immediate impact on the business regardless of their role. Come work with us at our NYC headquarters.",
    "career_block_cta": "jobs@lalignenyc.com",
    "career_block_link": "mailto:jobs@lalignenyc.com",
    "collection_fillscreen": false,
    "collections_show_sale_indicator": true,
    "collections_show_sold_out_indicator": true,
    "collections_filter_size_enable": true,
    "filter_size": "XS, S, M, L, XL, 30x30, 32x30, 34x30",
    "product_help_button": "Email Styliste",
    "product_help_email": "#",
    "product_zoom_enable": true,
    "product_related_enable": true,
    "size_guide": "<table>\n\t\t\t<thead>\n\t\t\t\t<tr>\n\t\t\t\t\t<th>Size</th>\n\t\t\t\t\t<th>Bust</th>\n\t\t\t\t\t<th>Waist</th>\n\t\t\t\t\t<th>Waist</th>\n\t\t\t\t\t<th>Size</th>\n\t\t\t\t</tr>\n\t\t\t</thead>\n\t\t\t<tbody>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>0</td>\n\t\t\t\t\t<td>31\"</td>\n\t\t\t\t\t<td>26\"</td>\n\t\t\t\t\t<td>35.5\"</td>\n\t\t\t\t\t<td>XS</td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>2</td>\n\t\t\t\t\t<td>32\"</td>\n\t\t\t\t\t<td>27\"</td>\n\t\t\t\t\t<td>36.5\"</td>\n\t\t\t\t\t<td>S</td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>4</td>\n\t\t\t\t\t<td>33\"</td>\n\t\t\t\t\t<td>28\"</td>\n\t\t\t\t\t<td>37.5\"</td>\n\t\t\t\t\t<td>S</td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>6</td>\n\t\t\t\t\t<td>34\"</td>\n\t\t\t\t\t<td>29\"</td>\n\t\t\t\t\t<td>38.5\"</td>\n\t\t\t\t\t<td>M</td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>8</td>\n\t\t\t\t\t<td>35\"</td>\n\t\t\t\t\t<td>30\"</td>\n\t\t\t\t\t<td>39.5\"</td>\n\t\t\t\t\t<td>M</td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>10</td>\n\t\t\t\t\t<td>36\"</td>\n\t\t\t\t\t<td>31\"</td>\n\t\t\t\t\t<td>40.5\"</td>\n\t\t\t\t\t<td>L</td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td>12</td>\n\t\t\t\t\t<td>37\"</td>\n\t\t\t\t\t<td>32\"</td>\n\t\t\t\t\t<td>41.5\"</td>\n\t\t\t\t\t<td>L</td>\n\t\t</tr>\n\t\t<tr>\n<td>14</td>\n\t\t\t\t\t<td>40.5\"</td>\n\t\t\t\t\t<td>33\"</td>\n\t\t\t\t\t<td>43\"</td>\n\t\t\t\t\t<td>XL</td>\n\t\t</tr>\n\t\t<tr>\n<td>16</td>\n\t\t\t\t\t<td>45\"</td>\n\t\t\t\t\t<td>38\"</td>\n\t\t\t\t\t<td>48\"</td>\n\t\t\t\t\t<td>2X</td>\n\t\t</tr>\n\t\t<tr>\n<td>18</td>\n\t\t\t\t\t<td>47\"</td>\n\t\t\t\t\t<td>40\"</td>\n\t\t\t\t\t<td>50\"</td>\n\t\t\t\t\t<td>2X</td>\n\t\t</tr>\n\t\t<tr>\n<td>20</td>\n\t\t\t\t\t<td>49\"</td>\n\t\t\t\t\t<td>42\"</td>\n\t\t\t\t\t<td>52\"</td>\n\t\t\t\t\t<td>3X</td>\n\t\t</tr>\n\t\t<tr>\n<td>22</td>\n\t\t\t\t\t<td>51\"</td>\n\t\t\t\t\t<td>44\"</td>\n\t\t\t\t\t<td>54\"</td>\n\t\t\t\t\t<td>3X</td>\n\t\t\t\t</tr>\n\t\t\t</tbody>\n\t\t</table>",
    "cart_notes_enable": true,
    "cart_enable_ajax": true,
    "search_count": 48,
    "no_results_product_1": "",
    "no_results_product_2": "le-garcon-tee-white",
    "no_results_product_3": "",
    "mailchimp_link": "//lalignenyc.us12.list-manage.com/subscribe/post-json?u=50b4b4732bc77986e03cac398&amp;id=179280f8ea&c=?",
    "newsletter_title": "",
    "mailchimp_success": "",
    "mailchimp_failure": "",
    "instagram_link": "https://instagram.com/bloomglobal",
    "facebook_link": "http://facebook.com/bloomglobal",
    "pinterest_link": "https://www.pinterest.com/bloomglobal",
    "collection_title": "",
    "collection_description": "",
    "recommend": "",
    "enable_gdpr": true,
    "gdpr_message_title": "We care about your privacy",
    "gdpr_message": "<p>We use cookies and similar technologies to provide the best experience on our website. <a href=\"/pages/behind-the-label-1\" target=\"_blank\" title=\"Behind the Label\">Privacy Policy</a></p>",
    "gdpr_label_agree": "Ok",
    "gdpr_label_disagree": "No, Thanks",
    "checkout_header_image": "",
    "checkout_logo_image": "",
    "checkout_logo_position": "center",
    "checkout_logo_size": "large",
    "checkout_body_background_image": "",
    "checkout_body_background_color": "#ffffff",
    "checkout_input_background_color_mode": "white",
    "checkout_sidebar_background_image": "",
    "checkout_sidebar_background_color": "#eedbca",
    "checkout_heading_font": "Garamond, Baskerville, 'Baskerville Old Face', 'Hoefler Text', 'Times New Roman'",
    "checkout_body_font": "Helvetica Neue",
    "checkout_accent_color": "#eedbca",
    "checkout_button_color": "#000000",
    "checkout_error_color": "#f45b4f",
    "pt_apply_button_enable": true,
    "pt_apply_button_color": "#000000",
    "pt_apply_button_hover_color": "#000000",
    "pt_apply_button_disabled_color": "#000000",
    "mega_1_pic": "shopify://shop_images/mega_1_img.jpg",
    "mega_1_link": "https://lalignenyc.myshopify.com/collections/newest",
    "mega_1_text": "",
    "mega_2_pic": "shopify://shop_images/02_100118_0236_2048x2048_fdcf5994-8a2e-429a-bab4-c6f4058804d8.jpg",
    "mega_2_link": "https://lalignenyc.myshopify.com/collections/the-glass-house",
    "mega_2_text": "",
    "mega_3_pic": "",
    "mega_3_link": "",
    "mega_3_text": "",
    "mega_4_pic": "",
    "mega_4_link": "",
    "mega_4_text": "",
    "mega_5_link": "",
    "mega_5_text": "",
    "mega_6_link": "",
    "mega_6_text": "",
    "inline_featured_profile_1": "in-line/natasha-lyonne",
    "inline_featured_profile_2": "in-line/nicole-richie",
    "inline_featured_profile_3": "in-line/yaya-dacosta",
    "about_section_8": "",
    "about_section_9": "",
    "founders": "shopify://shop_images/mega_1_img.jpg",
    "founders_cta": "Drop us a line",
    "founders_link": "/pages/contact",
    "home_billboard_media": "slideshow",
    "bg_video_mp4": "",
    "bg_video_ogv": "",
    "bg_video_webm": "",
    "bg_video_poster": "",
    "slide_1": true,
    "slide_1_img": "",
    "slide_1_alt": "La Ligne",
    "slide_1_headline": "Slip Into Summer",
    "slide_1_subhead": "Your warm weather wardrobe has arrived.",
    "slide_1_cta": "SHOP OUR STRIPES",
    "slide_1_link": "https://lalignenyc.com/collections/all",
    "slide_1_align": "right",
    "slide_1_color": "light",
    "slide_2": true,
    "slide_2_img": "",
    "slide_2_alt": "La Ligne",
    "slide_2_headline": "<br> Get high with us <br>",
    "slide_2_subhead": "Introducing our High Notes <br> collaboration with Malin + Goetz",
    "slide_2_cta": "EXPLORE PRODUCT",
    "slide_2_link": "https://www.malinandgoetz.com/candles/la-ligne-high-notes-crew-tshirt-candle",
    "slide_2_align": "left",
    "slide_2_color": "light",
    "slide_3": true,
    "slide_3_img": "",
    "slide_3_alt": "La Ligne",
    "slide_3_headline": "Walk the line in our newest stripes",
    "slide_3_subhead": "",
    "slide_3_cta": "SHOP OUR STRIPES",
    "slide_3_link": "https://lalignenyc.com/collections/newest",
    "slide_3_align": "right",
    "slide_3_color": "dark",
    "intro_pre": "",
    "intro_text": "This just in!",
    "featured_content_1_enable": true,
    "featured_content_1_pic": "",
    "featured_content_1_split": false,
    "featured_content_1_title": "Dreamland",
    "featured_content_1_copy": "The summer essentials of your dreams.",
    "featured_content_1_cta": "VIEW COLLECTION",
    "featured_content_1_link": "https://lalignenyc.com/collections/dreamland",
    "featured_content_1_align": "right",
    "featured_content_1_color": "light",
    "featured_content_1_textblock": "We wanna be on you.",
    "featured_content_2_enable": true,
    "featured_content_2_pic": "",
    "featured_content_2_split": false,
    "featured_content_2_title": "Martha Martha Martha",
    "featured_content_2_copy": "Cozy up to us!",
    "featured_content_2_cta": "VIEW COLLECTION",
    "featured_content_2_link": "https://lalignenyc.myshopify.com/collections/martha-martha-martha",
    "featured_content_2_align": "left",
    "featured_content_2_color": "dark",
    "featured_content_2_textblock": "The Stripe:",
    "featured_content_3_enable": true,
    "featured_content_3_pic": "",
    "featured_content_3_split": false,
    "featured_content_3_title": "The Glass House",
    "featured_content_3_copy": "Fall in line.",
    "featured_content_3_cta": "View collection",
    "featured_content_3_link": "/collections/the-glass-house",
    "featured_content_3_align": "left",
    "featured_content_3_color": "light",
    "featured_content_3_textblock": "Timeless.",
    "featured_content_4_enable": true,
    "featured_content_4_pic": "",
    "featured_content_4_split": false,
    "featured_content_4_title": "Monogram",
    "featured_content_4_copy": "Hi we're La Ligne and we are monogramahalics.",
    "featured_content_4_cta": "View collection",
    "featured_content_4_link": "collections/monogram-story",
    "featured_content_4_align": "right",
    "featured_content_4_color": "light",
    "featured_content_4_textblock": "Bold.",
    "featured_content_5_enable": true,
    "featured_content_5_pic": "",
    "featured_content_5_split": false,
    "featured_content_5_title": "La Vie En Rose",
    "featured_content_5_copy": "Your staples for spring.",
    "featured_content_5_cta": "View Collection",
    "featured_content_5_link": "collections/la-vie-en-rose",
    "featured_content_5_align": "left",
    "featured_content_5_color": "light",
    "featured_content_5_textblock": "Universal.",
    "featured_content_6_enable": true,
    "featured_content_6_pic": "",
    "featured_content_6_split": false,
    "featured_content_6_title": "La Paradisiaque",
    "featured_content_6_copy": "A seasonal reinvention of the stripes and lines we love.",
    "featured_content_6_cta": "View Collection",
    "featured_content_6_link": "collections/la-paradisiaque",
    "featured_content_6_align": "right",
    "featured_content_6_color": "light",
    "featured_content_6_textblock": "Democratic.",
    "featured_content_7_enable": true,
    "featured_content_7_pic": "",
    "featured_content_7_split": false,
    "featured_content_7_title": "To Whom it Maye Concern",
    "featured_content_7_copy": "Fall in line with our collection of timeless staples.",
    "featured_content_7_cta": "View Collection",
    "featured_content_7_link": "collections/to-whom-it-maye-concern",
    "featured_content_7_align": "left",
    "featured_content_7_color": "light",
    "featured_content_7_textblock": "La Ligne.",
    "featured_content_8_enable": true,
    "featured_content_8_pic": "",
    "featured_content_8_split": false,
    "featured_content_8_title": "Leave 'em Breathless",
    "featured_content_8_copy": "The baseline. Your go-to pieces for every season.",
    "featured_content_8_cta": "View Collection",
    "featured_content_8_link": "/collections/leave-em-breathless",
    "featured_content_8_align": "right",
    "featured_content_8_color": "dark",
    "featured_content_8_textblock": "",
    "featured_content_9_enable": true,
    "featured_content_9_pic": "",
    "featured_content_9_split": true,
    "featured_content_9_title": "Between the Lines",
    "featured_content_9_copy": "Who we are. <br>\nWhat we are. <br>\nWhy we are.",
    "featured_content_9_cta": "Learn More",
    "featured_content_9_link": "/pages/behind-the-label",
    "featured_content_9_align": "left",
    "featured_content_9_color": "dark",
    "featured_content_9_textblock": "",
    "featured_content_10_enable": true,
    "featured_content_10_pic": "",
    "featured_content_10_split": false,
    "featured_content_10_title": "In Line",
    "featured_content_10_copy": "An ongoing portrait series featuring\nthe ladies we love — get to know our bande.",
    "featured_content_10_cta": "See More",
    "featured_content_10_link": "blogs/in-line",
    "featured_content_10_align": "right",
    "featured_content_10_color": "light",
    "featured_content_10_textblock": "",
    "featured_content_11_enable": true,
    "featured_content_11_pic": "",
    "featured_content_11_split": false,
    "featured_content_11_title": "Shop La Ligne",
    "featured_content_11_copy": "The line starts here.",
    "featured_content_11_cta": "Shop All",
    "featured_content_11_link": "/collections/all",
    "featured_content_11_align": "left",
    "featured_content_11_color": "light",
    "featured_content_11_textblock": "",
    "featured_content_12_enable": true,
    "featured_content_12_pic": "",
    "featured_content_12_split": true,
    "featured_content_12_title": "En Ligne",
    "featured_content_12_copy": "Follow us, share us, like us.",
    "featured_content_12_cta": "@lalignenyc",
    "featured_content_12_link": "https://www.instagram.com/lalignenyc/",
    "featured_content_12_align": "left",
    "featured_content_12_color": "light",
    "featured_content_12_textblock": "",
    "related_count": "2",
    "monogram_disclosure": "Preview shows color and arrangement only. Not to scale.",
    "shop_img_alt": "La Ligne - Shop",
    "shop_img_headline": "The Full Lineup",
    "shop_img_text": "Shop all the classics and discover a few modern twists. We are now dropping new product every week, so check back for what's next in line.",
    "shop_img_color": "light",
    "product_monogram_text": "<p>Our \"slash\" monogram is inspired by the tradition of crossing out one's name on personalized stationery to indicate a more casual, friendly relationship with the recipient.</p>\n<p></p>\n<p>Single Letter Monogram<br>The slash appears through the singular letter, which is typically one's first or last initial.</p>\n<p></p>\n<p>Two Letter Monogram<br>The two letter monogram is typically the initials of one's first and last names (although feel free to get creative). The slash will appear through the second letter.</p>\n<p></p>\n<p>Three Letter Monogram<br>In the case of the three letter monogram, the initial of one's last name is typically placed in the center, with first and middle initials placed on either side. The slash appears through the center letter.</p>",
    "shop_slide_1": true,
    "shop_slide_1_alt": "Shop",
    "shop_slide_1_headline": "The Full Lineup",
    "shop_slide_1_text": "Shop all the classics and discover a few modern twists. We are now dropping new product every week, so check back for what's next in line.",
    "shop_slide_1_align": "left",
    "shop_slide_1_color": "light",
    "shop_slide_2": true,
    "shop_slide_2_alt": "alt",
    "shop_slide_2_headline": "Headline",
    "shop_slide_2_text": "This is text",
    "shop_slide_2_align": "left",
    "shop_slide_2_color": "dark",
    "shop_slide_3": false,
    "shop_slide_3_alt": "",
    "shop_slide_3_headline": "",
    "shop_slide_3_text": "",
    "shop_slide_3_align": "left",
    "shop_slide_3_color": "light",
    "in_line_video": "",
    "mega_1": "Shop",
    "mega_1_img": "false",
    "mega_1_list_1": "",
    "mega_1_list_2": "",
    "mega_1_list_3": "",
    "mega_2": "",
    "mega_2_img": "false",
    "mega_2_list_1": "",
    "mega_2_list_2": "",
    "mega_2_list_3": "",
    "mega_3": "",
    "mega_3_img": "false",
    "mega_3_list_1": "",
    "mega_3_list_2": "",
    "mega_3_list_3": "",
    "mega_4": "",
    "mega_4_img": "false",
    "mega_4_list_1": "",
    "mega_4_list_2": "",
    "mega_4_list_3": "",
    "mega_5": "",
    "mega_5_img": "false",
    "mega_5_list_1": "",
    "mega_5_list_2": "",
    "mega_5_list_3": "",
    "mega_6": "",
    "mega_6_img": "false",
    "mega_6_list_1": "",
    "mega_6_list_2": "",
    "mega_6_list_3": "",
    "slider_fillscreen": false,
    "slider_home_auto": true,
    "slider_home_show_dots": true,
    "slider_home_show_arrows": true,
    "slider_home_rate": "5000",
    "slider_home_transition": "slide",
    "slide_1_mobile": false,
    "slide_2_mobile": false,
    "slide_3_mobile": false,
    "sizeguide_pdf": "https://cdn.shopify.com/s/files/1/2233/8277/files/LaLigne_Size_Guide.pdf?3322045413752173795",
    "twitter_link": "http://twitter.com/bloomglobal",
    "google_plus_link": "",
    "tumblr_link": "",
    "youtube_link": "https://www.youtube.com/user/bloomglobal",
    "vimeo_link": "https://vimeo.com/bloomglobal",
    "fancy_link": "",
    "rss_link": "",
    "social_sharing_products": true,
    "social_sharing_blog": true,
    "social_sharing_count": false,
    "share_facebook": true,
    "share_twitter": true,
    "share_pinterest": true,
    "share_fancy": true,
    "share_google": true,
    "instagram_widget": false,
    "instagram_client_id": "",
    "instagram_username": "",
    "instagram_count": "",
    "bg_photo_cred": "",
    "featured_content_1_full": false,
    "featured_content_2_full": false,
    "featured_content_3_full": false,
    "featured_content_4_full": false,
    "featured_content_5_full": false,
    "featured_content_6_full": false,
    "enable_featured_collection": false,
    "home_featured_collection": "",
    "enable_featured_article": false,
    "home_featured_article": "",
    "cart_promo": "Cart promo message can be edited in theme settings",
    "product_meta_text": "",
    "customer_service_enable": true,
    "customer_service_headline": "Customer Service",
    "customer_service_text": "We look forward to hearing from you! If you’re calling about an order, please have your confirmation number ready.",
    "customer_service_cta": "LOU@LALIGNENYC.COM (917) 979-2680",
    "customer_service_link": "mailto:lou@lalignenyc.com",
    "inquiries_enable": true,
    "inquiries_headline": "Is This Pressing?",
    "inquiries_text": "For press inquiries, please email:",
    "inquiries_cta": "LALIGNE@DERRIS.COM",
    "inquiries_link": "mailto:laligne@derris.com",
    "hiring_enable": true,
    "hiring_headline": "We're Hiring",
    "hiring_text": "Have you earned your e-commerce stripes? We're seeking talented people to join our fast growing company. Email your resume to: jobs@lalignenyc.com",
    "hiring_cta": "JOBS@LALIGNENYC.COM",
    "hiring_link": "mailto:jobs@lalignenyc.com",
    "contact_social_enable": true,
    "contact_social_headline": "En Ligne",
    "contact_social_text": "Follow us, share us, like us.",
    "contact_social_cta": "@lalignenyc",
    "contact_social_link": "https://www.instagram.com/lalignenyc/",
    "compliment_color": "#caceac",
    "about_content_block_1": true,
    "about_content_block_2": true,
    "about_content_block_3": false,
    "enable_shop_promo": "true",
    "video_mp4.mp4": "https://cdn.shopify.com/s/files/1/2233/8277/files/small.mp4?4006786292150397201",
    "video_ogv.ogv": "https://cdn.shopify.com/s/files/1/2233/8277/files/small.ogv?4361286793378975585",
    "video_webm.webm": "",
    "shop_slide_1_mobile": false,
    "shop_slide_1_subhead": "Shop all the classics and discover a few modern twists",
    "shop_slide_2_mobile": false,
    "shop_slide_2_subhead": "Text",
    "shop_slide_3_mobile": false,
    "shop_slide_3_subhead": "",
    "shop_headline": "The Full Lineup",
    "shop_text": "Shop all the classics and discover a few modern twists. We're now dropping new product every week, so check back for what's next in line.",
    "footer_bg": "#4a4a4a",
    "footer_text_color": "#fff",
    "footer_menu": "footer",
    "footer_social_enable": true,
    "footer_about": "",
    "footer_support": "",
    "assign_md1": "",
    "md1_text": "",
    "md1_mi1_text": "",
    "md1_mi1_link": "",
    "md1_mi2_text": "",
    "md1_mi2_link": "",
    "md1_mi3_text": "",
    "md1_mi3_link": "",
    "md1_mi4_text": "",
    "md1_mi4_link": "",
    "md1_mi5_text": "",
    "md1_mi5_link": "",
    "assign_md2": "",
    "md2_text": "",
    "md2_mi1_text": "",
    "md2_mi1_link": "",
    "md2_mi2_text": "",
    "md2_mi2_link": "",
    "md2_mi3_text": "",
    "md2_mi3_link": "",
    "md2_mi4_text": "",
    "md2_mi4_link": "",
    "md2_mi5_text": "",
    "md2_mi5_link": "",
    "assign_md3": "",
    "md3_text": "",
    "md3_mi1_text": "",
    "md3_mi1_link": "",
    "md3_mi2_text": "",
    "md3_mi2_link": "",
    "md3_mi3_text": "",
    "md3_mi3_link": "",
    "md3_mi4_text": "",
    "md3_mi4_link": "",
    "md3_mi5_text": "",
    "md3_mi5_link": "",
    "assign_md4": "",
    "md4_text": "",
    "md4_mi1_text": "",
    "md4_mi1_link": "",
    "md4_mi2_text": "",
    "md4_mi2_link": "",
    "md4_mi3_text": "",
    "md4_mi3_link": "",
    "md4_mi4_text": "",
    "md4_mi4_link": "",
    "md4_mi5_text": "",
    "md4_mi5_link": "",
    "featured_content_color_dark": "#000000",
    "featured_content_color_light": "#ffffff",
    "slider_home_dark": "#000000",
    "slider_home_light": "#ffffff",
    "promo_enable_mobile": true,
    "promo_alt": "",
    "promo_cta": "",
    "promo_link": "",
    "logo_max_width": "130",
    "checkout_use_storefront_logo": false,
    "sticky_header": true,
    "shop_collection_1_cta": "Build a Fresco",
    "shop_collection_1_link": "the-fresco",
    "shop_collection_2_cta": "Build a Nano",
    "shop_collection_2_link": "the-fresco",
    "collections_count_enable": true,
    "collections_tags_enable": true,
    "collections_products_per_row": "4",
    "collections_rows": "4",
    "collections_sort_enable": true,
    "collections_filter_enable": true,
    "collections_filter_color_enable": true,
    "filter_color": "Black, White, Gray, Blue, Green, Red, Yellow",
    "collections_filter_material_enable": false,
    "filter_material": "",
    "product_quantity_enable": true,
    "product_image_zoom_type": "",
    "product_thumbnails_position": "below",
    "product_options_placement": "bottom",
    "shop_collection_1": "the-fresco-chair",
    "shop_collection_2": "the-nano",
    "instagram_title": "Instagram",
    "transparent_header": true,
    "footer_information": "Bloom was founded by four dads wanting to bring meaningful innovation and contemporary design to a world of baby products that have traditionally been functional but not in tune with the design sense of modern parents.",
    "home_section_1": "slider",
    "home_section_2": "featured-products",
    "home_section_3": "",
    "home_section_4": "",
    "home_featured_product": "",
    "home_featured_products": "",
    "home_featured_products_num": "3",
    "home_featured_products_row_num": "3",
    "home_featured_products_show_heading": true,
    "home_page_content": "about-us",
    "home_page_show_heading": true,
    "slide_1_color_state": "light",
    "slide_1_text_align": "left",
    "slide_1_x": "left",
    "slide_1_y": "20%",
    "slide_2_color_state": "light",
    "slide_2_text_align": "left",
    "slide_2_x": "left",
    "slide_2_y": "20%",
    "slide_3_color_state": "dark",
    "slide_3_text_align": "left",
    "slide_3_x": "left",
    "slide_3_y": "10%",
    "slide_color_dark": "#000",
    "slide_color_light": "#fff",
    "assign_m2": "",
    "assign_m3": "",
    "assign_m4": "",
    "enable_global_banner": true,
    "global_banner_text": "hello",
    "global_banner_link": "http://google.com",
    "global_header_mode": "dark",
    "global_banner_dark": "#2d2d2d",
    "global_banner_dark_text": "#f0f0f0",
    "global_banner_light": "#efefef",
    "global_banner_light_text": "#2f2f2f",
    "footer_quicklinks_enable": true,
    "footer_quicklinks_linklist": "footer",
    "footer_second_menu_enable": true,
    "footer_second_menu": "footer",
    "footer_blog_enable": false,
    "footer_blog": "news",
    "footer_contact_enable": false,
    "footer_contact_text": "",
    "show_footer_lines": true,
    "page_list": "index,home page,",
    "slide_4": false,
    "slide_4_link": "",
    "slide_4_alt": "",
    "slide_5": false,
    "slide_5_link": "",
    "slide_5_alt": "",
    "slide_6": false,
    "slide_6_link": "",
    "slide_6_alt": "",
    "global_banner_bg": "#383838",
    "checkout_use_header_image": false,
    "checkout_logo": "",
    "checkout_use_body_background_image": false,
    "checkout_use_sidebar_background_image": false,
    "nav_below_logo": true,
    "left_aligned_logo": false,
    "show_promo_message": false,
    "promo_message": "This is a message in Theme Settings > Header > Top Bar",
    "promo_message_link": "http://google.com",
    "promo_message_placement": "top",
    "show_cart_icon": true,
    "show_cart_preview": false,
    "header_sociallinks_enable": true,
    "header_search_enable": true,
    "facebook_linky": "http://facebook.com/shopify",
    "site_width": "1440",
    "gutter_size_row": "30",
    "gutter_size_grid": "12",
    "mailchimp_action": "//lemonadeny.us3.list-manage.com/subscribe/post-json?u=c1f32a04076cca5892d2d5c7e&amp;id=315fd97389&c=?",
    "breadcrumbs_active": true,
    "color_body": "#000000",
    "color_header": "#000000",
    "color_link": "#2d3f34",
    "color_button_background": "#2d3f34",
    "color_button_text": "#ffffff",
    "color_border": "#cccccc",
    "color_notice": "#f6f6f6",
    "color_disabled": "#e2e2e2",
    "color_success": "#c13333",
    "color_warning": "#c16233",
    "color_error": "#33c13d",
    "social_twitter_link": "https://twitter.com/shopify",
    "social_facebook_link": "https://www.facebook.com/shopify",
    "social_pinterest_link": "https://www.pinterest.com/shopify",
    "social_google_plus_link": "",
    "social_instagram_link": "https://instagram.com/shopify",
    "social_tumblr_link": "",
    "social_youtube_link": "",
    "social_vimeo_link": "",
    "social_fancy_link": "",
    "social_rss_link": "",
    "sections": {
      "bxz_head": {
        "type": "bxz_head",
        "settings": {}
      },
      "bxz_modal": {
        "type": "bxz_modal",
        "settings": {}
      },
      "1571725804644": {
        "type": "two-block",
        "settings": {
          "high": true,
          "gap_between": false,
          "reverse_mobile": false,
          "overlay_background": "#000000",
          "overlay_background_opacity": 50,
          "two_block_1_image": "shopify://shop_images/20190715_ATY_LALIGNE_06_047-ATY2_2048x2048_07f1fe9c-704e-4267-854c-3c9dfed74bef.png",
          "two_block_1_video": "",
          "two_block_1_headline": "Heart to Hart",
          "two_block_1_button": "Shop New",
          "two_block_1_link": "shopify://collections",
          "two_block_1_d_headline": true,
          "two_block_1_d_text": true,
          "two_block_1_align": "left",
          "two_block_1_valign": "middle",
          "two_block_1_color": "light",
          "two_block_1_size": "half",
          "two_block_1_m_headline": true,
          "two_block_1_m_text": true,
          "two_block_1_m_align": "right",
          "two_block_1_m_valign": "bottom",
          "two_block_1_m_color": "light",
          "two_block_2_image": "shopify://shop_images/04_022619_094_copy_2048x2048_3b6dfbb6-b15a-4c8c-a8e5-783525ef81b9.jpg",
          "two_block_2_video": "",
          "two_block_2_headline": "Wilde Flower",
          "two_block_2_button": "Shop the Collection",
          "two_block_2_link": "shopify://collections/wilde-flower",
          "two_block_2_d_headline": true,
          "two_block_2_d_text": true,
          "two_block_2_align": "left",
          "two_block_2_valign": "middle",
          "two_block_2_color": "light",
          "two_block_2_size": "half",
          "two_block_2_m_headline": true,
          "two_block_2_m_text": true,
          "two_block_2_m_align": "right",
          "two_block_2_m_valign": "bottom",
          "two_block_2_m_color": "light"
        }
      },
      "1571728828157": {
        "type": "heading",
        "settings": {
          "text": "We Wanna Be on You."
        }
      },
      "1571729375053": {
        "type": "tiles",
        "settings": {
          "tile_1_image": "shopify://shop_images/20190715_ATY_LALIGNE_06_047-ATY2_2048x2048_07f1fe9c-704e-4267-854c-3c9dfed74bef.png",
          "tile_1_video": "",
          "tile_1_headline": "Le Drop",
          "tile_1_button": "shop newest",
          "tile_1_link": "shopify://collections/newest",
          "tile_1_d_headline": true,
          "tile_1_d_text": true,
          "tile_1_align": "left",
          "tile_1_valign": "bottom",
          "tile_1_color": "light",
          "tile_1_m_headline": true,
          "tile_1_m_text": true,
          "tile_1_m_align": "right",
          "tile_1_m_valign": "bottom",
          "tile_1_m_color": "light",
          "tile_2_image": "shopify://shop_images/04_022619_094_copy_2048x2048_3b6dfbb6-b15a-4c8c-a8e5-783525ef81b9.jpg",
          "tile_2_video": "",
          "tile_2_headline": "Unleash your Inner Boheme",
          "tile_2_button": "Shop Dresses",
          "tile_2_link": "shopify://collections/wilde-flower",
          "tile_2_d_headline": true,
          "tile_2_d_text": true,
          "tile_2_align": "right",
          "tile_2_valign": "bottom",
          "tile_2_color": "light",
          "tile_2_m_headline": true,
          "tile_2_m_text": true,
          "tile_2_m_align": "right",
          "tile_2_m_valign": "bottom",
          "tile_2_m_color": "light",
          "tile_3_image": "shopify://shop_images/20190715_ATY_LALIGNE_01_403-ATY2_2048x2048_2df1ed14-dc36-44d0-be70-a9919392960d.png",
          "tile_3_video": "",
          "tile_3_headline": "We Hart Jess",
          "tile_3_button": "Shop Tops",
          "tile_3_link": "shopify://collections/wilde-flower",
          "tile_3_d_headline": true,
          "tile_3_d_text": true,
          "tile_3_align": "right",
          "tile_3_valign": "bottom",
          "tile_3_color": "light",
          "tile_3_m_headline": true,
          "tile_3_m_text": true,
          "tile_3_m_align": "right",
          "tile_3_m_valign": "bottom",
          "tile_3_m_color": "light",
          "tile_4_image": "shopify://shop_images/featured_content_2_pic.jpg",
          "tile_4_video": "",
          "tile_4_headline": "Stories",
          "tile_4_button": "Read More",
          "tile_4_link": "shopify://blogs/news",
          "tile_4_d_headline": true,
          "tile_4_d_text": true,
          "tile_4_align": "right",
          "tile_4_valign": "bottom",
          "tile_4_color": "light",
          "tile_4_m_headline": true,
          "tile_4_m_text": true,
          "tile_4_m_align": "right",
          "tile_4_m_valign": "bottom",
          "tile_4_m_color": "light",
          "tile_5_image": "shopify://shop_images/02_100118_0236_2048x2048_fdcf5994-8a2e-429a-bab4-c6f4058804d8.jpg",
          "tile_5_video": "",
          "tile_5_headline": "Behind the Label",
          "tile_5_button": "Learn More",
          "tile_5_link": "shopify://pages/behind-the-label",
          "tile_5_d_headline": true,
          "tile_5_d_text": true,
          "tile_5_align": "center",
          "tile_5_valign": "top",
          "tile_5_color": "light",
          "tile_5_m_headline": true,
          "tile_5_m_text": true,
          "tile_5_m_align": "right",
          "tile_5_m_valign": "bottom",
          "tile_5_m_color": "light"
        }
      },
      "1571731334710": {
        "type": "heading",
        "settings": {
          "text": "The Stripes: Bold. Universal. Timeless. Democratic."
        }
      },
      "1571732056492": {
        "type": "one-block",
        "settings": {
          "image": "shopify://shop_images/Martha_5_2048x2048_960ab951-4e34-4235-bd6f-0c3df3292d4d.jpg",
          "video": "",
          "headline": "Heart to Hart",
          "button": "Shop New",
          "link": "shopify://collections",
          "d_headline": true,
          "d_text": true,
          "align": "right",
          "valign": "bottom",
          "color": "light",
          "m_headline": true,
          "m_text": true,
          "m_align": "right",
          "m_valign": "bottom",
          "m_color": "light"
        }
      },
      "1571733062769": {
        "type": "labande",
        "settings": {
          "title": "#WithLaBande",
          "labande_select": "feed",
          "labande_1_image": "shopify://shop_images/Ashley_Benson_La_Ligne_La_Bande_SEPT_2019_SET_2_6177_FINAL_BW_V2_flat_1024x1024_8fa6e8ac-dce5-4434-82f7-9de1f211d3dd.jpg",
          "labande_1_video": "",
          "labande_1_headline": "Ashley Benson",
          "labande_1_button": "Explore",
          "labande_1_link": "#",
          "labande_1_d_headline": true,
          "labande_1_d_text": true,
          "labande_1_align": "right",
          "labande_1_valign": "bottom",
          "labande_1_color": "light",
          "labande_1_m_headline": true,
          "labande_1_m_text": true,
          "labande_1_m_align": "right",
          "labande_1_m_valign": "bottom",
          "labande_1_m_color": "light",
          "labande_2_image": "shopify://shop_images/Victoria_Smith_and_Leah_La_Ligne_La_Bande_SEPT_2019_SET_2_3910_FINAL_BW_web_1024x1024_ce6a17a1-9e97-4a3f-8401-3d8ca51f2824.jpg",
          "labande_2_video": "",
          "labande_2_headline": "Victoria Smith",
          "labande_2_button": "Explore",
          "labande_2_link": "#",
          "labande_2_d_headline": true,
          "labande_2_d_text": true,
          "labande_2_align": "right",
          "labande_2_valign": "bottom",
          "labande_2_color": "light",
          "labande_2_m_headline": true,
          "labande_2_m_text": true,
          "labande_2_m_align": "right",
          "labande_2_m_valign": "bottom",
          "labande_2_m_color": "light",
          "labande_3_image": "shopify://shop_images/ViolettaKomyshan_LaLigneDec18_0051_FINAL_BW_web_1024x1024_9cdfafbf-44d2-433f-aab5-a750f9085ac6.jpg",
          "labande_3_video": "",
          "labande_3_headline": "Violetta Komyshan",
          "labande_3_button": "Explore",
          "labande_3_link": "#",
          "labande_3_d_headline": true,
          "labande_3_d_text": true,
          "labande_3_align": "right",
          "labande_3_valign": "bottom",
          "labande_3_color": "light",
          "labande_3_m_headline": true,
          "labande_3_m_text": true,
          "labande_3_m_align": "right",
          "labande_3_m_valign": "bottom",
          "labande_3_m_color": "light"
        }
      },
      "1571734013830": {
        "type": "two-block",
        "settings": {
          "high": false,
          "gap_between": true,
          "reverse_mobile": true,
          "overlay_background": "#ffffff",
          "overlay_background_opacity": 0,
          "two_block_1_image": "shopify://shop_images/02_100118_0236_2048x2048_fdcf5994-8a2e-429a-bab4-c6f4058804d8.jpg",
          "two_block_1_video": "",
          "two_block_1_headline": "En Ligne",
          "two_block_1_button": "@lalignenyc",
          "two_block_1_link": "#",
          "two_block_1_d_headline": true,
          "two_block_1_d_text": true,
          "two_block_1_align": "right",
          "two_block_1_valign": "bottom",
          "two_block_1_color": "light",
          "two_block_1_size": "one-third",
          "two_block_1_m_headline": true,
          "two_block_1_m_text": true,
          "two_block_1_m_align": "right",
          "two_block_1_m_valign": "bottom",
          "two_block_1_m_color": "light",
          "two_block_2_image": "shopify://shop_images/20190715_ATY_LALIGNE_06_047-ATY2_2048x2048_07f1fe9c-704e-4267-854c-3c9dfed74bef.png",
          "two_block_2_image_mobile": "shopify://shop_images/JoAni_Johnson_La_Ligne_La_Bande_SEPT_2019_Set_1_243_FINAL_web_b57f66fd-d7b3-48c1-b264-d16299e6dafa.jpg",
          "two_block_2_video": "",
          "two_block_2_headline": "In Line",
          "two_block_2_button": "MEET LA BANDE",
          "two_block_2_link": "shopify://blogs/journal",
          "two_block_2_d_headline": true,
          "two_block_2_d_text": true,
          "two_block_2_align": "left",
          "two_block_2_valign": "bottom",
          "two_block_2_color": "light",
          "two_block_2_size": "two-thirds",
          "two_block_2_m_headline": true,
          "two_block_2_m_text": true,
          "two_block_2_m_align": "left",
          "two_block_2_m_valign": "bottom",
          "two_block_2_m_color": "light"
        }
      },
      "mosaic": {
        "type": "mosaic",
        "blocks": {
          "1572285024299": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/1.jpg",
              "mosaic_link": "#",
              "mosaic_hide": true
            }
          },
          "1572285045141": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/2.jpg",
              "mosaic_link": "#",
              "mosaic_hide": false
            }
          },
          "1572285056538": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/3.jpg",
              "mosaic_link": "#",
              "mosaic_hide": false
            }
          },
          "1572285066488": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/4.jpg",
              "mosaic_link": "#",
              "mosaic_hide": false
            }
          },
          "1572285075579": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/5.jpg",
              "mosaic_link": "#",
              "mosaic_hide": false
            }
          },
          "1572385915813": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/6.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572385942117": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/7.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572385962716": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/8.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572385976192": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/9.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572385988159": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/10.jpg",
              "mosaic_link": "",
              "mosaic_hide": false
            }
          },
          "1572386002131": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/11.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572386011918": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/12.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572386025597": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/13.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572386035319": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/14.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572386045335": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/15.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          },
          "1572386055665": {
            "type": "select",
            "settings": {
              "mosaic_pic": "shopify://shop_images/16_12b66245-e6e0-4a63-9179-b89e64553e7c.jpg",
              "mosaic_link": "",
              "mosaic_hide": true
            }
          }
        },
        "block_order": [
          "1572285024299",
          "1572285045141",
          "1572285056538",
          "1572285066488",
          "1572285075579",
          "1572385915813",
          "1572385942117",
          "1572385962716",
          "1572385976192",
          "1572385988159",
          "1572386002131",
          "1572386011918",
          "1572386025597",
          "1572386035319",
          "1572386045335",
          "1572386055665"
        ],
        "settings": {
          "mosaic_headline": "Who Inspires Us."
        }
      },
      "how-it-works": {
        "type": "how-it-works",
        "blocks": {
          "ff3e2ef3-3041-45f2-b117-b312686357ad": {
            "type": "select",
            "settings": {
              "headline": "Log In",
              "text": "Use your email to create an account. It only takes a minute."
            }
          },
          "11e953ab-5e3d-40d3-8ef1-f1f8ed2b615b": {
            "type": "select",
            "settings": {
              "headline": "Find Your Item",
              "text": "Pick the item in your purchase history."
            }
          },
          "9859c38b-284f-4fac-8400-81bac2e2f8ed": {
            "type": "select",
            "settings": {
              "headline": "List Your Item",
              "text": "Give a brief description and we'll review your listing."
            }
          }
        },
        "block_order": [
          "ff3e2ef3-3041-45f2-b117-b312686357ad",
          "11e953ab-5e3d-40d3-8ef1-f1f8ed2b615b",
          "9859c38b-284f-4fac-8400-81bac2e2f8ed"
        ],
        "settings": {
          "title": "How It works"
        }
      },
      "preloved-accordion-buy": {
        "type": "preloved-accordion-buy",
        "blocks": {
          "68994057-47a3-45f6-b30b-945a32537b5f": {
            "type": "select",
            "settings": {
              "headline": "What can I find in La Ligne's Pre-Loved Collection?",
              "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru"
            }
          },
          "228a3b12-1c75-4324-8f07-4c179bb26900": {
            "type": "select",
            "settings": {
              "headline": "How do I pay for a Pre-Loved item?",
              "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru"
            }
          }
        },
        "block_order": [
          "68994057-47a3-45f6-b30b-945a32537b5f",
          "228a3b12-1c75-4324-8f07-4c179bb26900"
        ],
        "settings": {
          "title": "Frequently Asked Questions",
          "acc_title": "FAQ: I want to buy..."
        }
      },
      "preloved-accordion-sell": {
        "type": "preloved-accordion-sell",
        "blocks": {
          "4e975f20-ba8e-4596-954d-871debcbb720": {
            "type": "select",
            "settings": {
              "headline": "How do I sell a Pre-Loved item?",
              "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laboru"
            }
          }
        },
        "block_order": ["4e975f20-ba8e-4596-954d-871debcbb720"],
        "settings": {
          "acc_title_2": "FAQ: how i want to sell..."
        }
      },
      "featured-products": {
        "type": "featured-products",
        "settings": {
          "title": "Newest collection",
          "button_label": "",
          "button_link": ""
        }
      },
      "16589878235d8e8d99": {
        "type": "featured-products",
        "settings": {
          "title": "Newest collection",
          "thecollection": "",
          "button_label": "Shop all",
          "button_link": "shopify://collections/aaa-bold-stripe-sweater"
        }
      },
      "filter-menu-settings": {
        "type": "filter-menu-settings",
        "settings": {}
      }
    },
    "content_for_index": [
      "1571725804644",
      "1571728828157",
      "1571729375053",
      "1571731334710",
      "1571732056492",
      "1571733062769",
      "1571734013830",
      "16589878235d8e8d99"
    ],
    "blocks": {
      "10603822535667782919": {
        "type": "shopify://apps/wishlist/blocks/app-embed/7f9269b0-1b45-4d0c-8479-faf04f05d8ac",
        "disabled": true,
        "settings": {
          "hide_float_icon": false,
          "is_show_vendor": false,
          "heart_icon_color": "",
          "iwish_count_clr": "#ffffff",
          "iwish_float_custom_icon": "",
          "float_heart_position": "middle",
          "float_heart_alignment": "left",
          "open_drawer_once": false,
          "multi_category_wishlist": false,
          "is_old_cur_convertor": false,
          "drawer_is_add_all_to_cart": false,
          "cart_icon_class": ".cart-count-bubble",
          "iwish_img_col": "2",
          "iwish_img_size": "50X50",
          "is_multi_language": true,
          "drawer_title": "My Wishlist",
          "drawer_empty_description": "Explore more and shortlist some items",
          "drawer_empty_msg": "Your wishlist is empty!",
          "drawer_login_msg": "Wishlist is not saved permanently yet. Please <a class=\"link-text\" href=\"/account/login\">log in</a> or <a class=\"link-text\" href=\"/account/register\">Create Account</a> to save it.",
          "main_wishlist_text": "Main Wishlist",
          "save_btn_text": "SAVE"
        }
      }
    }
  },
  "presets": {
    "Matthew": {
      "breadcrumbs_active": true,
      "color_body": "#000000",
      "color_header": "#000000",
      "color_link": "#2d3f34",
      "color_button_background": "#2d3f34",
      "color_button_text": "#ffffff",
      "color_border": "#cccccc",
      "color_notice": "#f6f6f6",
      "color_disabled": "#e2e2e2",
      "color_success": "#c13333",
      "color_warning": "#c16233",
      "color_error": "#33c13d",
      "logo_use_image": true,
      "nav_below_logo": true,
      "left_aligned_logo": false,
      "favicon_enable": false,
      "show_promo_message": false,
      "promo_message_placement": "top",
      "show_cart_icon": true,
      "show_cart_preview": false,
      "header_sociallinks_enable": true,
      "header_search_enable": true,
      "footer_blog_enable": false,
      "footer_quicklinks_enable": false,
      "footer_quicklinks_linklist": "footer",
      "footer_second_menu_enable": false,
      "footer_second_menu": "",
      "footer_social_enable": true,
      "footer_contact_enable": false,
      "footer_contact_text": "",
      "footer_newsletter_enable": false,
      "show_footer_lines": true,
      "home_section_1": "slider",
      "home_section_2": "featured-products",
      "home_section_3": "",
      "home_section_4": "",
      "slider_home_auto": false,
      "slider_home_show_dots": true,
      "slider_home_rate": "5000",
      "slider_home_transition": "fade",
      "slide_1": true,
      "slide_2": false,
      "slide_3": false,
      "slide_4": false,
      "slide_5": false,
      "slide_6": false,
      "home_featured_products_num": "3",
      "home_featured_products_row_num": "3",
      "home_featured_products_show_heading": true,
      "home_page_show_heading": true,
      "collections_show_sale_indicator": true,
      "collections_show_sold_out_indicator": true,
      "collections_count_enable": true,
      "collections_tags_enable": true,
      "collections_products_per_row": "4",
      "collections_rows": "4",
      "collections_sort_enable": true,
      "collections_filter_enable": true,
      "collections_filter_color_enable": true,
      "filter_color": "Black, White, Gray, Blue, Green, Red, Yellow",
      "collections_filter_size_enable": true,
      "filter_size": "XS, S, M, L, XL, 30x30, 32x30, 34x30",
      "collections_filter_material_enable": false,
      "filter_material": "",
      "product_quantity_enable": true,
      "product_image_zoom_type": "zoom-in",
      "product_thumbnails_position": "below",
      "product_related_enable": true,
      "product_options_placement": "bottom",
      "cart_notes_enable": false,
      "cart_enable_ajax": true,
      "social_sharing_products": true,
      "social_sharing_blog": true,
      "social_sharing_count": false,
      "share_facebook": true,
      "share_twitter": true,
      "share_pinterest": true,
      "share_fancy": true,
      "share_google": true,
      "checkout_use_header_image": false,
      "checkout_logo": "",
      "checkout_logo_position": "left",
      "checkout_logo_size": "medium",
      "checkout_use_body_background_image": false,
      "checkout_body_background_color": "#ffffff",
      "checkout_input_background_color_mode": "white",
      "checkout_use_sidebar_background_image": false,
      "checkout_sidebar_background_color": "#fafafa",
      "checkout_heading_font": "Helvetica Neue",
      "checkout_body_font": "Helvetica Neue",
      "checkout_accent_color": "#f45b4f",
      "checkout_button_color": "#bbbbbb",
      "checkout_error_color": "#f45b4f"
    }
  }
}
